# Form implementation generated from reading ui file 'd:\final project1\qtdesign4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 860)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                  stop:0 #0f2027,\n"
"                                  stop:0.5 #203a43,\n"
"                                  stop:1 #2c5364);\n"
"}\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"\n"
"QPushButton#btnUpdate, QPushButton#btnExit {\n"
"    background-color: #e67e22;\n"
"}\n"
"\n"
"QPushButton#btnExit {\n"
"    background-color: #c0392b;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(450, 80, 571, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_5.setStyleSheet("background-color: #648bbf;\n"
"color: white;\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_3.setStyleSheet("background-color: #648bbf;\n"
"color: white;\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_4.setStyleSheet("background-color: #648bbf;\n"
"color: white;\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_2.setStyleSheet("background-color: #648bbf;\n"
"color: white;\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setStyleSheet("background-color: #648bbf;\n"
"color: white;\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 0, 691, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(";\n"
"color: white;\n"
"border-radius: 12px;\n"
"padding: 16px;\n"
"\n"
"font-size: 30px;\n"
"font-weight: bold;\n"
"")
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(450, 580, 571, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnUpdate = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btnUpdate.setStyleSheet("background-color: #475569; /* можно заменить на другой */\n"
"color: white;\n"
"border-radius: 8px;\n"
"padding: 16px;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout_2.addWidget(self.btnUpdate)
        self.btnExit = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btnExit.setStyleSheet("background-color: #475569; /* можно заменить на другой */\n"
"color: white;\n"
"border-radius: 8px;\n"
"padding: 16px;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout_2.addWidget(self.btnExit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "View Rooms"))
        self.pushButton_3.setText(_translate("MainWindow", "Make Reservation"))
        self.pushButton_4.setText(_translate("MainWindow", "View Reservations"))
        self.pushButton_2.setText(_translate("MainWindow", "Add Rooms"))
        self.pushButton.setText(_translate("MainWindow", "Cancel Reservation"))
        self.label.setText(_translate("MainWindow", "Hotel Reservation System"))
        self.btnUpdate.setText(_translate("MainWindow", "Update Reservation"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
