# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setPointSize(24)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #FDF2F3;  /* Ещё более светлый молочно-розовый */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setStyleSheet("QFrame {\n"
"    background-color: #b8a99a;\n"
"    border-radius: 16px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #2e4a50;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 80, 601, 641))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #b8a99a;\n"
"    border-radius: 16px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(70, 10, 461, 581))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton1 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton1.setStyleSheet("QPushButton {\n"
"    background-color: #FBE3E4;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2e4a50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6b19d;\n"
"}\n"
"")
        self.pushButton1.setObjectName("pushButton1")
        self.verticalLayout.addWidget(self.pushButton1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #FBE3E4;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2e4a50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6b19d;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #FBE3E4;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2e4a50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6b19d;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #FBE3E4;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2e4a50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6b19d;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #FBE3E4;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2e4a50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6b19d;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hotel Reservation"))
        self.pushButton1.setText(_translate("MainWindow", "New Reservation"))
        self.pushButton_2.setText(_translate("MainWindow", "View Reservation"))
        self.pushButton_3.setText(_translate("MainWindow", "Edit Reservation"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel Reservation"))
        self.pushButton_5.setText(_translate("MainWindow", "Exit"))
